name: Deploy Next.js App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
      - name: Lint application
        run: npm run lint
      - name: Build application
        run: npm run build
      - name: Build storybook
        run: npm run build-storybook